name: CI

on:
    pull_request:
    push:

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: $(cat .nvmrc)
                  cache: 'npm'

            - name: Install node dependencies and run Tests
              run: |
                - npm install
                - npm test
